export interface Profile {
    _id: string,
    name: string,
    username: string,
    email: string,
    banned: string,
    warnings: number,
    handle: string,
    bio: string,
    followers: string[],
    following: string[],
    joined_rooms: string[],
    last_login: string,
    last_active: string,
    avatar?: string,
    banner?: string,
    verified: boolean,
    is_deleted: false,
    createdAt: Date,
    updatedAt: Date
}
